// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SOMData;

namespace SOMData.Migrations
{
    [DbContext(typeof(SOMDbContext))]
    [Migration("20211015143247_Comp_PostTermReplace")]
    partial class Comp_PostTermReplace
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SOMData.Models.CompilationWorkspace", b =>
                {
                    b.Property<int>("CompilationWorkspaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Command")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommandParams")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompilationTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompileFrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompileTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParseLines")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostReplaceTerms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReplaceTerms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WrapExpression")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompilationWorkspaceId");

                    b.ToTable("CompilationWorkspaces");
                });

            modelBuilder.Entity("SOMData.Models.ConsoleCommand", b =>
                {
                    b.Property<int>("ConsoleCommandID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CommandAssembly")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CommandDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CommandLine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommandType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstanceType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ConsoleCommandID");

                    b.ToTable("ConsoleCommands");
                });
#pragma warning restore 612, 618
        }
    }
}
