// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage ;
using SOMData;

namespace SOMData.Migrations
{
    [DbContext(typeof(SOMDbContext))]
    partial class SOMDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SOMData.Models.CompilationWorkspace", b =>
                {
                    b.Property<int>("CompilationWorkspaceId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Command");

                    b.Property<string>("CommandParams");

                    b.Property<string>("CompilationTitle");

                    b.Property<string>("CompileFrom");

                    b.Property<string>("CompileTo");

                    b.Property<string>("ReplaceLines");

                    b.Property<string>("ReplaceTerms");

                    b.Property<string>("WrapExpression");

                    b.HasKey("CompilationWorkspaceId");

                    b.ToTable("CompilationWorkspaces");
                });
#pragma warning restore 612, 618
        }
    }
}
